# Generated by Django 5.2.12 on 2026-07-11 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_attendance_screen_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditlog',
            name='action',
            field=models.CharField(choices=[('password_change_self', 'تغيير كلمة المرور (ذاتي)'), ('password_change_admin', 'تعيين كلمة مرور (مدير)'), ('user_login', 'تسجيل دخول'), ('session_revoke', 'إنهاء جلسة'), ('session_revoke_all', 'إنهاء كل الجلسات')], db_index=True, max_length=40, verbose_name='رمز العملية'),
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40, unique=True, verbose_name='مفتاح الجلسة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='User-Agent')),
                ('device_label', models.CharField(blank=True, default='', max_length=120, verbose_name='الجهاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='بدء الجلسة')),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='آخر نشاط')),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='وقت الإنهاء')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_web_sessions', to=settings.AUTH_USER_MODEL, verbose_name='أُنهيت بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_sessions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جلسة ويب',
                'verbose_name_plural': 'جلسات الويب',
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'revoked_at', '-last_seen_at'], name='core_userse_user_id_4bc3ca_idx')],
            },
        ),
    ]
