# Generated by Django 5.2.12 on 2026-09-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_user_session_tracking'),
        ('setup', '0015_workflow_whatsapp_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_administrations',
            field=models.ManyToManyField(blank=True, help_text='يقيّد رؤية المستخدم على موظفي هذه الإدارات فقط', related_name='assigned_users', to='setup.administration', verbose_name='الإدارات المرتبطة'),
        ),
    ]
