# Generated by Django 5.2.12 on 2026-10-07 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_accountant_view_only_policy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpendingaction',
            name='accountant_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المحاسب'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='accountant_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد المحاسب'),
        ),
        migrations.AddField(
            model_name='historicalpendingaction',
            name='accountant_reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='اعتماد المحاسب'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='accountant_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المحاسب'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='accountant_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ اعتماد المحاسب'),
        ),
        migrations.AddField(
            model_name='pendingaction',
            name='accountant_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountant_reviewed_actions', to=settings.AUTH_USER_MODEL, verbose_name='اعتماد المحاسب'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='returned_from_stage',
            field=models.CharField(blank=True, choices=[('branch', 'مدير الفرع'), ('gm', 'المدير العام'), ('officer', 'موظف الموارد'), ('accountant', 'المحاسب')], default='', max_length=10, verbose_name='المرحلة التي رُجِع منها'),
        ),
        migrations.AlterField(
            model_name='historicalpendingaction',
            name='status',
            field=models.CharField(choices=[('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار المدير العام'), ('pending_officer', 'بانتظار موظف الموارد'), ('pending_accountant', 'بانتظار المحاسب'), ('approved', 'مُنفَّذ'), ('returned', 'مُرتجَع للتعديل')], db_index=True, default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='returned_from_stage',
            field=models.CharField(blank=True, choices=[('branch', 'مدير الفرع'), ('gm', 'المدير العام'), ('officer', 'موظف الموارد'), ('accountant', 'المحاسب')], default='', max_length=10, verbose_name='المرحلة التي رُجِع منها'),
        ),
        migrations.AlterField(
            model_name='pendingaction',
            name='status',
            field=models.CharField(choices=[('pending_branch', 'بانتظار مدير الفرع'), ('pending_gm', 'بانتظار المدير العام'), ('pending_officer', 'بانتظار موظف الموارد'), ('pending_accountant', 'بانتظار المحاسب'), ('approved', 'مُنفَّذ'), ('returned', 'مُرتجَع للتعديل')], db_index=True, default='pending_branch', max_length=20, verbose_name='الحالة'),
        ),
    ]
