# Generated by Django 5.2.12 on 2026-10-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0043_employee_search_payroll_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='الاسم بالإنجليزية'),
        ),
    ]
