# Generated by Django 5.2.12 on 2026-10-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0044_employee_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birth_date_hijri',
            field=models.CharField(blank=True, help_text='يُعبّأ تلقائياً من التاريخ الميلادي (YYYY/MM/DD) ويمكن تعديله ليطابق الهوية.', max_length=10, verbose_name='تاريخ الميلاد الهجري'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='birth_date_hijri',
            field=models.CharField(blank=True, help_text='يُعبّأ تلقائياً من التاريخ الميلادي (YYYY/MM/DD) ويمكن تعديله ليطابق الهوية.', max_length=10, verbose_name='تاريخ الميلاد الهجري'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='birth_date_hijri',
            field=models.CharField(blank=True, help_text='يُعبّأ تلقائياً من التاريخ الميلادي (YYYY/MM/DD) ويمكن تعديله ليطابق الهوية.', max_length=10, verbose_name='تاريخ الميلاد الهجري'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد'),
        ),
        migrations.AddField(
            model_name='historicalemploymentrequest',
            name='birth_date_hijri',
            field=models.CharField(blank=True, help_text='يُعبّأ تلقائياً من التاريخ الميلادي (YYYY/MM/DD) ويمكن تعديله ليطابق الهوية.', max_length=10, verbose_name='تاريخ الميلاد الهجري'),
        ),
    ]
