# Generated by Django 5.2.12 on 2026-10-08 19:16

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0045_employee_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('effective_date', models.DateField(db_index=True, verbose_name='تاريخ السريان')),
                ('old_basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الأساسي السابق')),
                ('new_basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الأساسي الجديد')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='السبب')),
                ('applied', models.BooleanField(db_index=True, default=False, verbose_name='طُبِّق على ملف الموظف')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التطبيق')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_changes', to='employees.employee', verbose_name='الموظف')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_changes', to='employees.employeestatement', verbose_name='سجل التعديل')),
            ],
            options={
                'verbose_name': 'تعديل راتب',
                'verbose_name_plural': 'تعديلات الرواتب',
                'ordering': ['effective_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEmployeeSalaryChange',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='تاريخ التحديث')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='محذوف')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحذف')),
                ('effective_date', models.DateField(db_index=True, verbose_name='تاريخ السريان')),
                ('old_basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الأساسي السابق')),
                ('new_basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='الأساسي الجديد')),
                ('reason', models.CharField(blank=True, max_length=300, verbose_name='السبب')),
                ('applied', models.BooleanField(db_index=True, default=False, verbose_name='طُبِّق على ملف الموظف')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التطبيق')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أُضيف بواسطة')),
                ('employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employee', verbose_name='الموظف')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='employees.employeestatement', verbose_name='سجل التعديل')),
            ],
            options={
                'verbose_name': 'historical تعديل راتب',
                'verbose_name_plural': 'historical تعديلات الرواتب',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
