# Generated by Django 5.2.12 on 2026-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_workflow_whatsapp_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowwhatsappsettings',
            name='recipient_phones',
            field=models.JSONField(blank=True, default=dict, help_text='مفاتيح: system_admin, hr_manager, admin_manager, branch_manager, hr_officer, branch_accountant', verbose_name='جوال واتساب حسب الدور'),
        ),
    ]
